name       : kglobalaccel
version    : 5.68.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/kglobalaccel-5.68.0.tar.xz : 2eb710a3f29cbc8b7875fb3e8315d7c8e3b5bb93867e0a34cd5cdbac690bcbbf
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Global desktop keyboard shortcuts
description: |
    KGlobalAccel allows you to have global accelerators that are independent of the focused window. Unlike regular shortcuts, the application's window does not need focus for them to be activated.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kservice-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
