name       : kglobalaccel
version    : 5.38.1
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.38/kglobalaccel-5.38.1.tar.xz : 36ceeb585598c088c80fdde30b3ea9b12e6d250dcae46c24024072a37a5f236a
license    : LGPL-2.1
component  : desktop.library
summary    : Global desktop keyboard shortcuts
description: |
    KGlobalAccel allows you to have global accelerators that are independent of the focused window. Unlike regular shortcuts, the application's window does not need focus for them to be activated.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kservice-devel
    - kwindowsystem-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
