name       : kglobalaccel
version    : 5.58.0
release    : 28
source     :
    - https://download.kde.org/stable/frameworks/5.58/kglobalaccel-5.58.0.tar.xz : 4fd49052697d4659f793b8f7d678a9333a850ed6cf17472eaba9c023430b5bbf
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Global desktop keyboard shortcuts
description: |
    KGlobalAccel allows you to have global accelerators that are independent of the focused window. Unlike regular shortcuts, the application's window does not need focus for them to be activated.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kservice-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
