name       : kglobalaccel
version    : 5.40.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/kglobalaccel-5.40.0.tar.xz : f66970fd45c6917840d5eb1d64b6732b4612fd27602144d587d00f4b979e54e3
license    : LGPL-2.1
component  : desktop.library
summary    : Global desktop keyboard shortcuts
description: |
    KGlobalAccel allows you to have global accelerators that are independent of the focused window. Unlike regular shortcuts, the application's window does not need focus for them to be activated.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kservice-devel
    - kwindowsystem-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
