name       : kglobalaccel
version    : 5.36.0
release    : 4
source     :
    - https://download.kde.org/stable/frameworks/5.36/kglobalaccel-5.36.0.tar.xz : 729562dcaa1fea9f18b57a39a680276d1fdfd1b3333d4308e6c5218b061775da
license    : LGPL-2.1
component  : desktop.library
summary    : Global desktop keyboard shortcuts
description: |
    KGlobalAccel allows you to have global accelerators that are independent of the focused window. Unlike regular shortcuts, the application's window does not need focus for them to be activated.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kservice-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
