name       : kglobalaccel
version    : 5.49.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/kglobalaccel-5.49.0.tar.xz : 147ed37e1ceb39d4d40e5e94a73e8b9519be7da9f08eea23aefa64eebee267ba
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Global desktop keyboard shortcuts
description: |
    KGlobalAccel allows you to have global accelerators that are independent of the focused window. Unlike regular shortcuts, the application's window does not need focus for them to be activated.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kservice-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
