name       : kglobalaccel
version    : 5.94.0
release    : 65
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.94/kglobalaccel-5.94.0.tar.xz : a34b00116a72d0973cdeb203a5d237da63cc307e9e294dfaedb00ff0a36835e9
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Global desktop keyboard shortcuts
description: |
    KGlobalAccel allows you to have global accelerators that are independent of the focused window. Unlike regular shortcuts, the application's window does not need focus for them to be activated.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
