name       : kglobalaccel
version    : 5.79.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/kglobalaccel-5.79.0.tar.xz : c8778522f31a677d99b199247b43858ad4aa3e6c5db3f6a6aa84ac53c7de1d63
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Global desktop keyboard shortcuts
description: |
    KGlobalAccel allows you to have global accelerators that are independent of the focused window. Unlike regular shortcuts, the application's window does not need focus for them to be activated.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb-keysyms)
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
