name       : kglobalaccel
version    : 5.60.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/kglobalaccel-5.60.0.tar.xz : 660f2b930fd2ea4ad935f37d4e26253a7537ff30cf665ac57a41087dd4c2e805
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Global desktop keyboard shortcuts
description: |
    KGlobalAccel allows you to have global accelerators that are independent of the focused window. Unlike regular shortcuts, the application's window does not need focus for them to be activated.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kservice-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
